#!/bin/sh

set -e

version="$1"

# passing the kernel version is required
[ -z "$version" ] && exit 1

rm -rf /boot/*-$version || true

# Exynos 5422 (XU3 / XU4)
rm -rf /boot/exynos5422-odroidxu3.dtb || true
rm -rf /media/boot/exynos5422-odroidxu3.dtb || true

rm -rf /boot/exynos5422-odroidxu3.dts || true
rm -rf /media/boot/exynos5422-odroidxu3.dts || true

# AMLogic S805 (C1 / C0)
rm -rf /boot/meson8b_odroidc.dtb || true
rm -rf /media/boot/meson8b_odroidc.dtb || true

rm -rf /boot/meson8b_odroidc.dts || true
rm -rf /media/boot/meson8b_odroidc.dts || true

# AMLogic S905 (C2)
rm -fr /boot/meson64_odroidc2.dtb || true
rm -fr /boot/meson64_odroidc2.dtb || true

rm -fr /boot/meson64_odroidc2.dts || true
rm -fr /boot/meson64_odroidc2.dts || true

